default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: cats_pjs_development

test:
  <<: *default
  database: cats_pjs_test

staging:
  <<: *default
  database: cats_pjs_staging
  username: <%= Rails.application.credentials.STAGING_DB_USERNAME %>
  password: <%= Rails.application.credentials.STAGING_DB_PASSWORD %>

production:
  <<: *default
  database: cats_pjs_production
  username: <%= Rails.application.credentials.PRODUCTION_DB_USERNAME %>
  password: <%= Rails.application.credentials.PRODUCTION_DB_PASSWORD %>
